version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: stoktakip-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stoktakip

  backend:
    build: ./backend
    container_name: stoktakip-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/stoktakip
      PORT: 5000
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: stoktakip-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
